
#library(xlsx)
# run once, takes a while
#df <- read.xlsx("653001_Final_Excel_121914.xlsx", 1, 
#                stringsAsFactors=F)
#save(df, file="653001_Final_Excel_121914_xlsx.Rdata")
load("653001_Final_Excel_121914_xlsx.Rdata")

df$qs1 <- as.character(df$qs1)
north_side_zips <- c("60645", "60626", "60631", "60646", "60659",
                     "60660", "60640", "60625", "60630", "60656",
                     "60634", "60641", "60618", "60613", "60657",
                     "60707", "60739", "60647", "60614", "60651",
                     "60622", "60661", "60610", "60654", "60611",
                     "60601", "60602", "60603", "60604", "60605", 
                     "60606", "60607", "60612", "60624", "60644")
south_side_zips <- c("60623", "60608", "60616", "60632", "60609",
                     "60653", "60615", "60638", "60629", "60636",
                     "60621", "60637", "60649", "60619", "60620",
                     "60652", "60617", "60628", "60643", "60655",
                     "60827", "60633")
df$side <- rep(NA, nrow(df))
df$side[df$qs1 %in% north_side_zips] <- "north"
df$side[df$qs1 %in% south_side_zips] <- "south"

# add attributes to data cols to give the survey question text
q_text <- c("qs1", "Please provide your zip code.",
            "qs2_1", "Do you or any member of your immediate family work in any of the following industries? Select all that apply. | 1. Advertising / Market Research / Marketing (TERMINATE)",
            "qs2_2", "Do you or any member of your immediate family work in any of the following industries? Select all that apply. | 2. Public Relations / Journalism (TERMINATE)",
            "qs2_3", "Do you or any member of your immediate family work in any of the following industries? Select all that apply. | 3. Insurance company or Agent of an insurance company (TERMINATE)",
            "qs2_4", "Do you or any member of your immediate family work in any of the following industries? Select all that apply. | 4. Law firm or legal profession (TERMINATE)",
            "qs2_5", "Do you or any member of your immediate family work in any of the following industries? Select all that apply. | 5. None of the above",
            "qs3", "Which of the following ranges includes your age? | 1. Under 18 (TERMINATE),2. 18-24,3. 25-34,4. 35-44,5. 45-54,6. 55-64,7. 65 and over",
            "qs4", "What is your gender? | 1. Male,2. Female",
            "qs5_1", "Which of the following social media sites are you a member of? Select all that apply. | 1. Facebook",
            "qs5_2", "Which of the following social media sites are you a member of? Select all that apply. | 2. Twitter (TERMINATE if NOT selected)",
            "qs5_3", "Which of the following social media sites are you a member of? Select all that apply. | 3. LinkedIn",
            "qs5_4", "Which of the following social media sites are you a member of? Select all that apply. | 4. Google+",
            "qs5_5", "Which of the following social media sites are you a member of? Select all that apply. | 5. Pinterest",
            "qs5_6", "Which of the following social media sites are you a member of? Select all that apply. | 6. Instagram",
            "qs5_7", "Which of the following social media sites are you a member of? Select all that apply. | 7. Myspace",
            "qs5_8", "Which of the following social media sites are you a member of? Select all that apply. | 8. Other",
            "qs5_9", "Which of the following social media sites are you a member of? Select all that apply. | 9. None of the above",
            "qs5_8_other", "Which of the following social media sites are you a member of? Select all that apply. | Other",
            "qs6", "How often do you visit Twitter? | 1. Daily,2. A few times per week,3. Once a week,4. Every 2-3 weeks (TERMINATE),5. Once a month (TERMINATE),6. Less than once a month (TERMINATE)",
            "qs7_1", "Which of the following devices do you currently own? Select all that apply. | 1. Tablet PC",
            "qs7_2", "Which of the following devices do you currently own? Select all that apply. | 2. Laptop PC",
            "qs7_3", "Which of the following devices do you currently own? Select all that apply. | 3. Desktop PC",
            "qs7_4", "Which of the following devices do you currently own? Select all that apply. | 4. Smartphone (TERMINATE if NOT selected)",
            "qs7_5", "Which of the following devices do you currently own? Select all that apply. | 5. Mobile phone (not a smartphone)",
            "qs7_6", "Which of the following devices do you currently own? Select all that apply. | 6. Gaming console",
            "qs7_7", "Which of the following devices do you currently own? Select all that apply. | 7. HDTV",
            "qs7_8", "Which of the following devices do you currently own? Select all that apply. | 8. Internet-enabled TV, often known as a SMART TV",
            "qs7_9", "Which of the following devices do you currently own? Select all that apply. | 9. None of the above",
            "qs8", "Which devices do you use most often to connect to the Internet?",
            "qs9", "What is the make and model of your primary smartphone? e.g. Samsung Galaxy, iPhone 5, etc.",
            "qs10", "What is the primary way that you connect to the Internet? | 1. Broadband at home (Cable, DSL, etc),2. Phone plan with data included,3. Public WiFi,4. Public computer center,5. Other,",
            "qs10_5_other", "What is the primary way that you connect to the Internet? | Other",
            "qs11", "Have you ever heard of the “Smart Chicago Collaborative”? | 1. Yes,2. No,3. Don’t Know",
            "qs12", "Have you ever heard of the “Chicago Department of Public Health”? | 1. Yes,2. No,3. Don’t Know",                        
            "q1", "Have you ever been a victim of food poisoning?",
            "q2_1", "During or after your illness, which of the following did you do? Select all that apply. | 1. Went to the emergency room",
            "q2_2", "During or after your illness, which of the following did you do? Select all that apply. | 2. Looked up my symptoms online",
            "q2_3", "During or after your illness, which of the following did you do? Select all that apply. | 3. Called / Visited a doctor",
            "q2_4", "During or after your illness, which of the following did you do? Select all that apply. | 4. Called 311",
            "q2_5", "During or after your illness, which of the following did you do? Select all that apply. | 5. Called the restaurant where the illness was contracted",
            "q2_6", "During or after your illness, which of the following did you do? Select all that apply. | 6. Contacted the health department",
            "q2_7", "During or after your illness, which of the following did you do? Select all that apply. | 7. Contacted a lawyer",
            "q2_8", "During or after your illness, which of the following did you do? Select all that apply. | 8. None of the above",
            "q3_1", "Who did you tell about your illness? Select all that apply. | 1. Family",
            "q3_2", "Who did you tell about your illness? Select all that apply. | 2. Coworkers",
            "q3_3", "Who did you tell about your illness? Select all that apply. | 3. Friends on a social networking site (Ask Q3a)",
            "q3_4", "Who did you tell about your illness? Select all that apply. | 4. Other: __",
            "q3_5", "Who did you tell about your illness? Select all that apply. | 5. None of the above",
            "q3_4_other", "Who did you tell about your illness? Select all that apply.",
            "q3a_1", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 1. Facebook",
            "q3a_2", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 2. Twitter",
            "q3a_3", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 3. LinkedIn",
            "q3a_4", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 4. Google+",
            "q3a_5", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 5. Pinterest",
            "q3a_6", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 6. Instagram",
            "q3a_7", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 7. Myspace",
            "q3a_8", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 8. Other________",
            "q3a_9", "Which social networking sites did you use to tell about the food poisoning? Select all that apply. | 9. None of the above",
            "q4", "Have you ever reported a case of food poisoning to the Chicago health department?",
            "q5", "Did you ever look up the results of your report?",
            "q6_1", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 1. Go to the emergency room",
            "q6_2", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 2. Look up my symptoms online",
            "q6_3", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 3. Call / Visit a doctor",
            "q6_4", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 4. Call 311",
            "q6_5", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 5. Call the restaurant where the illness was contracted",
            "q6_6", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 6. Contact the health department",
            "q6_7", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 7. Contact a lawyer",
            "q6_8", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, what would you do? Select all that apply. | 8. Would not do anything",
            "q7_1", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 1. Family",
            "q7_2", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 2. Coworkers",
            "q7_3", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 3. Facebook friends",
            "q7_4", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 4. Twitter followers",
            "q7_5", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 5. Instagram followers",
            "q7_6", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 6. Yelp!",
            "q7_7", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 7. Other:___",
            "q7_8", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply. | 8. None of the above",
            "q7_7_other", "If you were to get food poisoning (insert the word “again” if Q1=1) from a restaurant in the future, who would you tell about your illness? Select all that apply.",
            "q8_1", "If you were to report a case of food poisoning to the Chicago health department, how confident are you that your report would be followed up on? (Scale 1 ‘Not at all confident’ to 10 ‘Extremely confident’)",
            "q9", 'To what extent do you agree or disagree with the following statement: “In the event that you or somebody in your family became ill after eating at a restaurant, it is your civic duty to report the illness to the authorities.”',
            "q10_1", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 1. Official health department / 311 website",
            "q10_2", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 2. Third party hosted website that is sanctioned by the health department",
            "q10_3", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 3. A robust privacy policy",
            "q10_4", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 4. Mobile friendly webpage / form",
            "q10_5", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 5. Assurance that the health department would follow up on my complaint",
            "q10_6", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 6. None, I would report it just because they asked me too",
            "q10_7", "Suppose further that you received a reply to your tweet with a link that enabled you to report your illness to the health department. Which of the following would you need to see in order to report the illness to the health department? Select all that apply. | 7. None, I would not be willing to report my illness to the health department",
            "q11_1", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 1. Name",
            "q11_2", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 2. Home address",
            "q11_3", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 3. Phone number",
            "q11_4", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 4. Twitter name (handle)",
            "q11_5", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 5. Email address",
            "q11_6", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 6. Restaurant name and address",
            "q11_7", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 7. Name or location of medical professional seen (if any)",
            "q11_8", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 8. Details about what you ate and how you became ill",
            "q11_9", "In relation to your illness, what details would you be willing to provide in your report? Select all that apply. | 9. None of the above",
            "q12", "Please tell us why you would not be willing to report your illness to the health department.",
            "q13_1", "If you did report an illness to the Chicago health department, how would you like to receive a follow up? Select all that apply. | 1. Phone",
            "q13_2", "If you did report an illness to the Chicago health department, how would you like to receive a follow up? Select all that apply. | 2. Email",
            "q13_3", "If you did report an illness to the Chicago health department, how would you like to receive a follow up? Select all that apply. | 3. Letter via USPS",
            "q13_4", "If you did report an illness to the Chicago health department, how would you like to receive a follow up? Select all that apply. | 4. Twitter",
            "q13_5", "If you did report an illness to the Chicago health department, how would you like to receive a follow up? Select all that apply. | 5. I would not like to receive a follow up",
            "q14", "To what extent do you agree or disagree with the following statement: “I am okay with a person or an organization that I do not follow on Twitter replying to a tweet that I send out.” | 1. Strongly disagree,2. Disagree,3. Neither agree nor disagree,4. Agree,5. Strongly agree,6. Not sure",
            "q15_1", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 1. White / Caucasian",
            "q15_2", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 2. Black / African American",
            "q15_3", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 3. Hispanic / Latino",
            "q15_4", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 4. Asian / Pacific Islander",
            "q15_5", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 5. Native American",
            "q15_6", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 6. Other",
            "q15_6_other", "Thank you for your input.  We just have two more demographic questions.  Which of the following best describes your race? Select all that apply. | 6. Other",
            "q16", "Which of the following ranges includes your gross yearly household income? | 1. Less than $20,000,2. $20,000 - $49,999,3. $50,000 - $74,999,4. $75,000 - $99,999,5. $100,000 and over,6. Prefer not to answer"
           )
q_text <- matrix(q_text, ncol=2, byrow=TRUE)
for(i in 1:nrow(q_text)){
  attr(df[,q_text[i,1]], "question_text") <- q_text[i,2]
}

save(df, file="653001_Final_Excel_121914_xlsx.Rdata")
